
import { Injectable, signal, computed, effect } from '@angular/core';

export type Language = 'en' | 'ar';

@Injectable({
    providedIn: 'root'
})
export class LanguageService {
    private currentLangSignal = signal<Language>((localStorage.getItem('lang') as Language) || 'en');

    currentLang = computed(() => this.currentLangSignal());

    constructor() {
        // Apply direction on initialization
        effect(() => {
            const lang = this.currentLang();
            document.documentElement.lang = lang;
            document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
            localStorage.setItem('lang', lang);

            // Update body class for font switching if needed
            if (lang === 'ar') {
                document.body.classList.add('font-arabic');
            } else {
                document.body.classList.remove('font-arabic');
            }
        });
    }

    setLanguage(lang: Language) {
        this.currentLangSignal.set(lang);
    }

    toggleLanguage() {
        this.setLanguage(this.currentLang() === 'en' ? 'ar' : 'en');
    }

    // Basic translation helper
    translate(key: string): string {
        const lang = this.currentLang();
        // Check if key exists in current language, if not try the key itself as a fallback if it's dynamic data
        return this.translations[lang][key] || key;
    }

    private translations: Record<Language, Record<string, string>> = {
        en: {
            'nav.home': 'Home',
            'nav.sports': 'Sports',
            'nav.entertainment': 'Entertainment',
            'nav.trains': 'Trains',
            'nav.stores': 'Stores',
            'nav.faq': 'FAQ',
            'nav.about': 'About',
            'nav.contact': 'Contact',
            'nav.ai_assistant': 'AI Assistant',
            'nav.login': 'Login',
            'nav.signup': 'Sign Up',
            'nav.my_bookings': 'My Bookings',
            'nav.settings': 'Settings',
            'nav.logout': 'Logout',
            'nav.admin_dashboard': 'Admin Dashboard',
            'home.title': 'Tazkarty',
            'home.subtitle': 'Your online partner to book your next Ticket In Egypt',
            'home.search_placeholder': 'Search by artist, event, or venue...',
            'home.search_btn': 'Search',
            'home.featured_title': 'Featured Highlights',
            'home.featured_subtitle': 'The most anticipated matches and shows',
            'home.view_all': 'View All',
            'Cairo International Stadium': 'Cairo International Stadium',
            'Borg El Arab Stadium': 'Borg El Arab Stadium',
            'Suez Canal Stadium': 'Suez Canal Stadium',
            'Al Ahly': 'Al Ahly',
            'Zamalek': 'Zamalek',
            'Al Masry': 'Al Masry',
            'Pyramids': 'Pyramids',
            'Modern Future': 'Modern Future',
            'Egyptian Premier League': 'Egyptian Premier League',
            'Egypt Cup': 'Egypt Cup',
            'home.book_now': 'Book Tickets Now',
            'home.why_title': 'Why Choose Tazkarty?',
            'home.why_subtitle': 'We provide the most seamless and secure booking experience in Egypt.',
            'home.instant_booking': 'Instant Booking',
            'home.instant_desc': 'Skip the lines. Book your tickets in seconds with our optimized checkout flow.',
            'home.diverse_selection': 'Diverse Selection',
            'home.diverse_desc': 'From underground gigs to stadium concerts, we have the largest event inventory.',
            'home.secure_payments': 'Secure Payments',
            'home.secure_desc': 'Bank-grade security with Stripe integration ensuring your data is always safe.',
            'trains.hero_title': 'The Art of Travel',
            'trains.hero_subtitle': 'Seamless Rail Journeys from Cairo',
            'trains.hero_desc': 'From the timeless majesty of the Nile to the Mediterranean’s eternal breeze. Experience the heritage of Egypt in unparalleled comfort and style.',
            'trains.where_to': 'Where to?',
            'trains.travel_date': 'Travel Date',
            'trains.search_trains': 'Search Trains',
            'trains.available_expeditions': 'Available Expeditions',
            'trains.transit': 'Transit',
            'trains.departure': 'Departure',
            'trains.arrival': 'Arrival',
            'trains.intermediate_stops': 'Intermediate Stops',
            'trains.no_trains_found': 'No Expeditions Found',
            'trains.no_trains_found_desc': "We couldn't find any available train schedules for this destination at the moment.",
            'trains.syncing': 'Synchronizing Schedules...',
            'trains.voyage_to': 'Voyage to',
            'ai.title': 'Nada',
            'ai.subtitle': 'Your personal travel & event concierge',
            'ai.quick_questions': 'Quick Questions',
            'ai.new_chat': 'New Chat',
            'ai.chat_with': 'Chat with Nada',
            'ai.chat_desc': 'Ask me about events, train schedules, or bookings!',
            'ai.online': 'Online',
            'ai.meet_nada': 'Meet Nada',
            'ai.meet_nada_desc': "I'm your AI concierge. I can help you discover exciting events, check train schedules, and manage your bookings across Egypt.",
            'ai.you': 'You',
            'ai.placeholder': 'Ask about events, trains, or help...',
            'ai.send': 'Send',
            'ai.disclaimer': 'AI responses may not always be accurate. Check official listings for critical updates.',
            'ai.welcome_guest': "Hi there! 👋 I'm Nada, your Tazkarty AI assistant. For the best experience and personalized recommendations, please log in to your account.",
            'ai.welcome_auth': "Hi there! 👋 I'm Nada, your Tazkarty AI assistant. I can help you find events, book tickets, and get smart recommendations. What would you like to do today?",
            'ai.error_session': 'Sorry, I could not start a chat session. Please try again later.',
            'ai.error_message': 'Sorry, something went wrong while talking to the AI. Please try again.',
            'ai.confirm_new_chat': 'Start a new chat? Current conversation will be cleared.',
            'ai.suggestion.movies': 'What movies are playing this week?',
            'ai.suggestion.concerts': 'Show me concerts near me',
            'ai.suggestion.alex_train': 'How can I book a train to Alexandria?',
            'ai.suggestion.tomorrow_trains': 'What are the train schedules for tomorrow?',
            'ai.suggestion.recommendations': 'I need recommendations',
            'ai.suggestion.carriage': 'How do I choose a carriage type?',
            'ai.suggestion.train_seats': 'Are there available seats for Aswan?',
            'ai.example.today': "🎬 What's showing today?",
            'ai.example.weekend': '🎵 Any concerts this weekend?',
            'ai.example.aswan': '🚆 Cairo to Aswan schedules',
            'ai.example.sports': '⚽ Sports events near me',
            'ai.example.recommend': '💡 Recommend something',
            'ai.example.train_how': '📱 How to book a train ticket?',
            'events.sports_title': 'Sports',
            'events.sports_subtitle': 'Book your seat for the most thrilling matches and championships across Egypt.',
            'events.ent_title': 'Entertainment',
            'events.ent_subtitle': 'Experience the magic of cinema, music, and theater.',
            'events.discover_title': 'Discover Events',
            'events.discover_subtitle': 'Browse upcoming movies, concerts, and shows near you.',
            'events.choose_team': 'Choose Team',
            'events.stadium': 'Stadium',
            'events.tournament': 'Tournament',
            'events.all_teams': 'All Teams',
            'events.all_stadiums': 'All Stadiums',
            'events.all_tournaments': 'All Tournaments',
            'events.clear_filters': 'Clear Filters',
            'events.events_found': 'Events Found',
            'events.no_matches': 'No matches found',
            'events.no_events': 'No events found',
            'events.no_matches_desc': "We couldn't find any matches for the selected team or criteria.",
            'events.no_events_desc': "We couldn't find any events matching your criteria.",
            'events.previous': 'Previous',
            'events.next': 'Next',
            'events.page': 'Page',
            'events.of': 'of',
            'events.tag.category': 'Category',
            'events.tag.venue': 'Venue Filter',
            'events.tag.search': 'Search',
            'events.tag.team': 'Team',
            'events.tag.stadium': 'Stadium',
            'events.tag.tournament': 'Tournament',
            'events.sold_out': 'Sold Out',
            'events.ai_pick': 'AI Pick',
            'events.trending': 'Trending',
            'events.start_from': 'Start',
            'events.book': 'Book',
            'events.unavailable': 'Unavailable',
            'events.about': 'About the Event',
            'events.select_section': 'Select Section',
            'events.select_showtime': 'Select Showtime',
            'events.booking_details': 'Booking Details',
            'events.secure_spot': 'Secure your spot now',
            'events.selected_section': 'Selected Section',
            'events.fan_id': 'Fan ID (Auto)',
            'events.full_name': 'Full Name',
            'events.ticket_count': 'Number of Tickets',
            'events.discount_code': 'Discount Code / QR',
            'events.apply': 'Apply',
            'events.total_amount': 'Total Amount',
            'events.book_now': 'Book Now',
            'events.select_seats': 'Select Seats',
            'events.date': 'Date',
            'events.time': 'Time',
            'events.price': 'Price',
            'events.gate': 'Gate',
            'events.section_guide': 'Select a section to proceed',
            'events.showtime_guide': 'Select a showtime to proceed',
            'events.loading_details': 'Loading event details...',
            'events.discount_placeholder': 'Enter code',
            'events.discount_success': 'Discount applied!',
            'events.secure_proceed': 'Proceed to secure payment',
            'events.power_by': 'Powered by Tazkarty Secure Checkout',
            'events.not_found': 'Event Not Found',
            'events.back_to_list': 'Back to Events',
            'events.no_shows': 'No showtimes available currently.',
            'events.no_sections': 'No sections info available currently.',
            'footer.about_text': 'Your premier destination for event and cinema ticket booking in Egypt.',
            'footer.quick_links': 'Quick Links',
            'footer.support': 'Support',
            'footer.contact_us': 'Contact Us',
            'footer.help_center': 'Help Center',
            'footer.terms': 'Terms of Service',
            'footer.privacy': 'Privacy Policy',
            'footer.refund_policy': 'Refund Policy',
            'footer.rights': 'All rights reserved.',
            'nav.notifications': 'Notifications',
            'nav.no_notifications': 'No new notifications',
            'sports.title': 'Sports',
            'sports.events': 'Events',
            'sports.subtitle': 'Book your seat for the most thrilling matches and championships across Egypt.',
            'ent.title': 'Entertainment',
            'ent.shows': 'Shows',
            'ent.subtitle': 'Experience the magic of cinema, music, and theater.',
            'common.no_results': 'No results found',
            'common.loading': 'Loading...',
            'common.featured': 'Featured',
            'team.Al Ahly': 'Al Ahly',
            'team.Zamalek': 'Zamalek',
            'team.Al Masry': 'Al Masry',
            'team.Pyramids': 'Pyramids',
            'team.Modern Future': 'Modern Future',
            'tournament.Egyptian Premier League': 'Egyptian Premier League',
            'tournament.Egypt Cup': 'Egypt Cup',
            'stadium.Cairo International Stadium': 'Cairo International Stadium',
            'stadium.Borg El Arab Stadium': 'Borg El Arab Stadium',
            'stadium.Suez Canal Stadium': 'Suez Canal Stadium',
            'faq.title': 'Frequently Asked Questions',
            'faq.q1': 'How can I book a ticket?',
            'faq.a1': 'You can book tickets directly through our website by selecting an event, choosing your preferred seats, and proceeding to checkout.',
            'faq.q2': 'Where can I pick up my physical ticket?',
            'faq.a2': 'You can visit any of our authorized stores listed on the "Stores" page. Please bring your booking reference ID.',
            'faq.q3': 'Can I cancel or refund my ticket?',
            'faq.a3': 'Refund policies vary by organizer. Generally up to 48 hours before.',
            'faq.q4': 'How do I access my mobile ticket?',
            'faq.a4': 'QR codes are available in the "My Bookings" section of your profile.',
            'faq.q5': 'Do I need to print my ticket?',
            'faq.a5': 'A digital QR code is usually sufficient.',
            'faq.q6': 'Is it safe to pay online?',
            'faq.a6': 'Yes, we use industry-standard encryption and secure gateways.',
            'store.cairo.name': 'Tazkarty Cairo Hub',
            'store.alex.name': 'Alexandria Sea View',
            'store.giza.name': 'Giza Pyramids Office',
            'store.nasr.name': 'Nasr City Branch',
            'store.cairo.addr': '123 Downtown Street, Cairo',
            'store.alex.addr': '45 Corniche Rd, Alexandria',
            'store.giza.addr': '88 Al Haram St, Giza',
            'store.nasr.addr': 'City Stars Mall, Phase 2',
            'store.hours': 'Opening Hours',
            'store.view_map': 'View on Map',
            'store.subtitle': 'Visit our authorized ticket centers to purchase tickets, pick up reservations, or get assistance.',
            'store.official': 'Official Store',
            'common.address': 'Address',
            'common.phone': 'Phone',
            'common.select': 'Select',
            'common.general': 'General',
            'common.venue': 'Venue',
            'common.stadium': 'Stadium',
            'common.and': 'and',
            'common.cairo_egypt': 'Cairo, Egypt',
            'Venue': 'Venue',
            'Stadium': 'Stadium',
            'TBA': 'TBA',
            'common.id': 'ID',
            'common.na': 'N/A',
            'Sports': 'Sports',
            'Entertainment': 'Entertainment',
            'movie': 'Movie',
            'concert': 'Concert',
            'sports': 'Sports',
            'show': 'Show',
            'entertainment': 'Entertainment',
            'trains': 'Trains',
            'home.stay_tuned': 'Stay Tuned!',
            'home.stay_tuned_desc': 'Our admins are currently hand-picking the most exciting events for you. Check back soon for featured highlights!',
            'contact.get_in_touch': 'Get in Touch',
            'contact.title': 'Contact Us',
            'contact.subtitle': "Have questions about your booking? Need technical support? We're here to help!",
            'contact.support_title': 'Customer Support',
            'contact.support_desc': 'Our support team is available 24/7 to assist you.',
            'contact.email_title': 'Email Us',
            'contact.email_desc': "Send us an email and we'll get back to you within 24 hours.",
            'contact.hq_title': 'Headquarters',
            'contact.hq_addr': '123 Digital Avenue, Tech District, Cairo, Egypt',
            'contact.form_title': 'Send us a Message',
            'contact.form_success': 'Message Sent!',
            'contact.form_success_desc': 'Thank you for contacting us. We will respond shortly.',
            'contact.name': 'Your Name',
            'contact.name_placeholder': 'John Doe',
            'contact.email': 'Email Address',
            'contact.email_placeholder': 'john@example.com',
            'contact.subject': 'Subject',
            'contact.subject_placeholder': 'Select a topic',
            'contact.msg': 'Message',
            'contact.msg_placeholder': 'How can we help you?',
            'contact.btn_sending': 'Sending...',
            'contact.btn_send': 'Send Message',
            'contact.topic.general': 'General Inquiry',
            'contact.topic.booking': 'Booking Support',
            'contact.topic.tech': 'Technical Issue',
            'contact.topic.feedback': 'Feedback',
            'contact.topic.partnership': 'Partnership',
            'faq.support_center': 'Support Center',
            'faq.subtitle': 'Find answers to common questions about booking, payments, and event attendance.',
            'faq.still_questions': 'Still have questions?',
            'faq.contact_support': 'Contact Support',
            'faq.still_desc': 'Our support team is available 24/7 to answer any other questions you may have about our services.',
            'faq.title_white': 'Frequently Asked',
            'faq.title_green': 'Questions',
            'contact.title_white': 'Contact',
            'contact.title_green': 'Us',
            'store.title_white': 'Our',
            'store.title_green': 'Stores',
            'about.our_story': 'Our Story',
            'about.title': 'About Tazkarty',
            'about.subtitle': 'Tazkarty is your premier destination for booking sports and entertainment events. We bridge the gap between fans and their favorite experiences with a seamless, secure, and user-friendly platform.',
            'about.meet_dev': 'Meet the Developer',
            'about.dev_exclusively': 'This application was developed exclusively by',
            'about.role': 'Lead Developer & Architect',
            'about.bio': 'A passionate full-stack developer dedicated to building seamless and intuitive digital experiences. Tazkarty is a culmination of modern web technologies designed to simplify event booking.',
            'about.special_thanks': 'Special Thanks & Acknowledgments',
            'about.vision_support': 'This project was made possible with the unwavering support and encouragement of my friends and colleagues. Thank you for believing in the vision.',
            'stepper.select_seats': 'Seat Selection',
            'stepper.checkout': 'Checkout',
            'stepper.confirmation': 'Confirmation',
            'settings.title': 'Account Settings',
            'settings.subtitle': 'Manage your profile and preferences',
            'settings.profile': 'Profile',
            'settings.security': 'Security',
            'settings.notifications': 'Notifications',
            'settings.account_mgmt': 'Account',
            'settings.profile_info': 'Profile Information',
            'settings.security_settings': 'Security Settings',
            'settings.notif_prefs': 'Notification Preferences',
            'settings.danger_zone': 'Account Management',
            'settings.full_name': 'Full Name',
            'settings.email': 'Email Address',
            'settings.phone': 'Phone Number',
            'settings.save_changes': 'Save Changes',
            'settings.saving': 'Saving...',
            'settings.current_pass': 'Current Password',
            'settings.new_pass': 'New Password',
            'settings.confirm_pass': 'Confirm New Password',
            'settings.change_pass': 'Change Password',
            'settings.update_success': 'Profile updated successfully!',
            'settings.update_failed': 'Failed to update profile',
            'settings.email_notif': 'Email Notifications',
            'settings.email_notif_desc': 'Receive booking confirmations via email',
            'settings.push_notif': 'Push Notifications',
            'settings.push_notif_desc': 'Get updates about your bookings',
            'settings.reminders': 'Event Reminders',
            'settings.reminders_desc': 'Get reminded about upcoming events',
            'settings.promo': 'Promotional Offers',
            'settings.promo_desc': 'Receive special offers and discounts',
            'settings.download_data': 'Download Your Data',
            'settings.download_data_desc': 'Get a copy of all your bookings and account information',
            'settings.download_btn': 'Download Data',
            'settings.delete_account': 'Delete Account',
            'settings.delete_account_desc': 'Permanently delete your account and all associated data. This action cannot be undone.',
            'settings.delete_btn': 'Delete My Account',
            'settings.delete_confirm': 'Are you sure you want to delete your account? This action cannot be undone!',
            'settings.delete_really': 'Really? All your data will be permanently deleted!',
            'settings.delete_request': 'Account deletion requested. Please contact support.',
            'booking.back_to_event': 'Back to Event',
            'booking.back_to_overview': 'Back to Overview',
            'booking.gates_open': 'Gates Open',
            'booking.match_start': 'Match Start',
            'booking.showtime': 'Showtime',
            'booking.confirm_booking': 'Confirm Booking',
            'booking.select_seats': 'Select Seats',
            'booking.select_seats_desc': 'Click on available seats to select/deselect',
            'booking.loading': 'Loading...',
            'booking.sports_event': 'Sports Event',
            'booking.match_day': 'Match Day',
            'booking.attendee': 'Attendee',
            'booking.guest_user': 'Guest User',
            'booking.section': 'Section',
            'booking.tickets_count': 'Ticket(s)',
            'booking.scan_gate': 'Scan at the gate',
            'booking.ref_id': 'Reference ID',
            'booking.need_to_know': 'Need to Know',
            'booking.sports_seat_guide': 'You are free to sit on any available seat within the section. Arrive early to get the best spots!',
            'booking.sold_out': 'Show Sold Out',
            'booking.browse_other': 'Browse Other Events',
            'booking.no_map': 'No seat map available for this show.',
            'booking.available': 'Available',
            'booking.selected': 'Selected',
            'booking.occupied': 'Occupied',
            'booking.vip': 'VIP',
            'booking.summary': 'Booking Summary',
            'booking.selected_seats': 'Selected Seats',
            'booking.max': 'Max',
            'booking.no_seats_selected': 'No seats selected yet.',
            'booking.click_map_start': 'Click on the map to start.',
            'booking.ticket_price': 'Ticket Price',
            'booking.booking_fee': 'Booking Fee',
            'booking.total': 'Total',
            'booking.checkout': 'Proceed to Checkout',
            'booking.processing': 'Processing...',
            'booking.terms_agree': 'By proceeding, you agree to our Terms of Service.',
            'booking.secure_checkout': 'Secure Checkout',
            'booking.secure_checkout_desc': 'Complete your booking securely with Stripe',
            'admin.dashboard': 'Dashboard',
            'admin.welcome': 'Welcome back!',
            'admin.happening_today': "Here's what's happening with Tazkarty today.",
            'admin.refresh': 'Refresh',
            'admin.export': 'Export Report',
            'admin.total_revenue': 'Total Revenue',
            'admin.total_bookings': 'Total Bookings',
            'admin.active_sports': 'Active Sports Events',
            'admin.total_users': 'Total Users',
            'admin.vs_last_month': 'vs last month',
            'admin.recent_bookings': 'Recent Bookings',
            'admin.view_all': 'View All',
            'admin.loading_bookings': 'Loading bookings...',
            'admin.no_bookings': 'No recent bookings',
            'admin.new_bookings_appear': 'New bookings will appear here',
            'admin.quick_actions': 'Quick Actions',
            'admin.manage_sports': 'Manage Sports Events',
            'admin.manage_stadiums': 'Manage Stadiums',
            'admin.manage_venues': 'Manage Venues',
            'admin.manage_ent': 'Manage Entertainment Events',
            'admin.manage_users': 'Manage Users',
            'admin.view_analytics': 'View Analytics',
            'admin.system_status': 'System Status',
            'admin.api_status': 'API Status',
            'admin.database': 'Database',
            'admin.socket_io': 'Socket.IO',
            'admin.payment_gateway': 'Payment Gateway',
            'admin.online': 'Online',
            'admin.connected': 'Connected',
            'admin.active': 'Active',
            'admin.event_mgmt': 'Event Management',
            'admin.event_mgmt_desc': 'Manage all events, movies, concerts, and shows',
            'admin.create_event': 'Create Event',
            'admin.search_placeholder': 'Search by title...',
            'admin.all_cities': 'All Cities',
            'admin.all_championships': 'All Championships',
            'admin.loading_events': 'Loading events...',
            'admin.active_badge': 'Active',
            'admin.inactive_badge': 'Inactive',
            'admin.featured_badge': 'Featured',
            'admin.edit': 'Edit',
            'admin.delete': 'Delete',
            'admin.no_events_found': 'No Events Found',
            'admin.adjust_filters': 'Try adjusting your filters',
            'admin.save': 'Save',
            'admin.cancel': 'Cancel',
            'admin.update': 'Update',
            'admin.create': 'Create',
            'admin.title': 'Title',
            'admin.description': 'Description',
            'admin.poster': 'Event Poster',
            'admin.match_details': 'Match Details',
            'admin.stadium': 'Stadium',
            'admin.home_team': 'Home Team',
            'admin.away_team': 'Away Team',
            'admin.total_cap': 'Total Capacity',
            'admin.home_cap': 'Home Users',
            'admin.away_cap': 'Away Users',
            'admin.gates_open': 'Gates Open At',
            'admin.duration': 'Duration (min)',
            'admin.release_date': 'Release Date',
            'admin.user_mgmt': 'User Management',
            'admin.user_mgmt_desc': 'Manage all registered users',
            'admin.export_users': 'Export Users',
            'admin.search_users_placeholder': 'Search by name or email...',
            'admin.role': 'Role',
            'admin.all_roles': 'All Roles',
            'admin.user': 'User',
            'admin.admin': 'Admin',
            'admin.joined': 'Joined',
            'admin.bookings': 'Bookings',
            'admin.spent': 'Total Spent',
            'admin.view': 'View',
            'admin.upgrade': 'Upgrade',
            'admin.downgrade': 'Downgrade',
            'admin.no_users_found': 'No Users Found',
            'admin.loading_users': 'Loading users...',
            'admin.account_status': 'Account Status',
            'admin.close': 'Close',
            'admin.phone': 'Phone',
            'admin.stadium_mgmt': 'Stadium Management',
            'admin.stadium_mgmt_desc': 'Manage stadiums, arenas, and sports venues',
            'admin.add_stadium': 'Add New Stadium',
            'admin.search_stadiums_placeholder': 'Search by name or location...',
            'admin.status_filter': 'Status Filter',
            'admin.all_stadiums': 'All Stadiums',
            'admin.active_only': 'Active Only',
            'admin.inactive_only': 'Inactive Only',
            'admin.loading_stadiums': 'Loading stadiums...',
            'admin.stadium_name': 'Stadium Name',
            'admin.location': 'Location',
            'admin.city': 'City',
            'admin.capacity': 'Capacity',
            'admin.manage_zones': 'Manage Zones/Halls',
            'admin.no_stadiums_found': 'No Stadiums Found',
            'admin.stadium_usage_desc': 'Try adjusting your filters or create a new stadium',
            'admin.add_first_stadium': 'Add First Stadium',
            'admin.sections': 'Sections',
            'admin.add_section': 'Add Section',
            'admin.no_sections_added': 'No sections added.',
            'admin.edit_section': 'Edit Section',
            'admin.add_new_section': 'Add New Section',
            'admin.section_name': 'Section Name',
            'admin.side_type': 'Side / Type',
            'admin.gate_entrance': 'Gate / Entrance',
            'admin.default_price': 'Default Price',
            'admin.seat_breakdown': 'Seat Breakdown',
            'admin.fill_all_fields': '⚠️ Please fill in all required fields (Title and Description)',
            'admin.select_stadium_error': '⚠️ Please select a stadium for sports events',
            'admin.select_teams_error': '⚠️ Please select both home and away teams',
            'admin.capacity_exceed_error': '⚠️ Total capacity exceeds stadium capacity!',
            'admin.capacity_sum_error': '⚠️ Sum of Home & Away exceeds stadium capacity!',
            'admin.event_update_success': '✅ Event updated successfully!',
            'admin.event_update_failed': '❌ Failed to update event',
            'admin.event_create_success': '✅ Event created successfully!',
            'admin.event_create_failed': '❌ Failed to create event',
            'admin.event_delete_success': '✅ Event deleted successfully!',
            'admin.event_delete_failed': '❌ Failed to delete event',
            'admin.delete_confirm': 'Are you sure you want to delete this event?',
            'admin.venue_mgmt': 'Venue Management',
            'admin.venue_mgmt_desc': 'Manage all venues, theaters, and event spaces',
            'admin.add_venue': 'Add New Venue',
            'admin.search_venues': 'Search Venues',
            'admin.search_venues_placeholder': 'Search by name or location...',
            'admin.all_venues': 'All Venues',
            'admin.loading_venues': 'Loading venues...',
            'admin.no_venues_found': 'No Venues Found',
            'admin.add_first_venue': 'Add First Venue',
            'admin.halls': 'Halls',
            'admin.manage_halls': 'Manage Halls',
            'admin.sellable': 'Sellable',
            'admin.shows': 'Shows',
            'admin.bookings_exist': 'Bookings Exist',
            'admin.edit_venue': 'Edit Venue',
            'admin.create_venue': 'Create New Venue',
            'admin.venue_name': 'Venue Name',
            'admin.venue_location': 'Location',
            'admin.venue_city': 'City',
            'admin.venue_capacity': 'Total Capacity',
            'admin.venue_image': 'Image URL',
            'admin.venue_description': 'Description',
            'admin.saving': 'Saving...',
            'admin.delete_venue_confirm': 'Are you sure you want to delete this venue?',
            'admin.delete_venue_warning': 'This action cannot be undone!',
            'admin.hall_name': 'Hall Name',
            'admin.hall_capacity': 'Hall Capacity',
            'admin.seat_breakdown_opt': 'Seat Breakdown (Optional)',
            'admin.add_hall': 'Add Hall',
            'admin.edit_hall': 'Edit Hall',
            'admin.save_hall': 'Save Hall',
            'admin.seat_map': 'Seat Map',
            'admin.venue_create_success': '✅ Venue created successfully',
            'admin.venue_update_success': '✅ Venue updated successfully',
            'admin.venue_delete_success': '✅ Venue deleted successfully',
            'admin.hall_save_success': '✅ Hall saved successfully',
            'admin.hall_save_error': '❌ Failed to save hall',
            'admin.hall_delete_success': '✅ Hall deleted successfully',
            'admin.fill_required_fields': '⚠️ Please fill in all required fields',
            'admin.venue_load_failed': '❌ Failed to load venues',
            'admin.venue_save_failed': '❌ Failed to save venue',
            'admin.venue_delete_failed': '❌ Failed to delete venue',
            'admin.venue_activated': '✅ Venue activated successfully',
            'admin.venue_deactivated': '✅ Venue deactivated successfully',
            'booking.order_summary': 'Order Summary',
            'booking.total_pay': 'Total Pay',
            'booking.secure_payment_title': '100% Secure Payment',
            'booking.secure_payment_desc': 'Your payment information is encrypted and processed securely by Stripe.',
            'booking.payment_details': 'Payment Details',
            'booking.card_number': 'Card Number',
            'booking.card_holder': 'Card Holder',
            'booking.expires': 'Expires',
            'booking.name_on_card': 'Name on Card',
            'booking.card_info': 'Card Information',
            'booking.pay_amount': 'Pay',
            'booking.powered_by': 'Powered by',
            'booking.confirmed': 'Booking Confirmed!',
            'booking.confirmed_desc': "Your tickets are ready! We've sent a detailed confirmation email to you.",
            'booking.return_home': 'Return to Home',
            'trains.carriage': 'Carriage',
            'trains.sync_station': 'Syncing with Station...',
            'trains.layout': 'Layout',
            'trains.res_summary': 'Reservation Summary',
            'trains.national_id': 'National ID (Required)',
            'trains.id_placeholder': '14 digits',
            'auth.welcome': 'Welcome Back!',
            'auth.signin_desc': 'Sign in to continue to Tazkarty',
            'auth.email': 'Email Address',
            'auth.email_placeholder': 'you@example.com',
            'auth.password': 'Password',
            'auth.password_placeholder': 'Enter your password',
            'auth.remember': 'Remember me',
            'auth.forgot': 'Forgot Password?',
            'auth.signin': 'Sign In',
            'auth.signing_in': 'Signing In...',
            'auth.no_account': "Don't have an account?",
            'auth.signup_now': 'Sign Up Now',
            'auth.admin_login': 'Admin Login',
            'auth.login_success': 'Login successful! Redirecting...',
            'auth.login_failed': 'Login failed. Please try again.',
            'auth.email_required': 'Email is required',
            'auth.email_invalid': 'Please enter a valid email',
            'auth.pass_required': 'Password is required (min 6 characters)',
            'auth.signup': 'Create Account',
            'auth.signup_desc': 'Join Tazkarty today and start exploring events.',
            'auth.fullname': 'Full Name',
            'auth.fullname_placeholder': 'Enter your full name',
            'auth.phone': 'Phone Number',
            'auth.phone_placeholder': '01xxxxxxxxx',
            'auth.national_id': 'National ID',
            'auth.id_placeholder': '14 digits',
            'auth.confirm_pass': 'Confirm Password',
            'auth.register': 'Sign Up',
            'auth.registering': 'Creating Account...',
            'auth.has_account': 'Already have an account?',
            'auth.login_now': 'Login Now',
            'auth.reg_success': 'Registration successful! Please login.',
            'auth.reg_failed': 'Registration failed. Please try again.',
            'auth.name_required': 'Full Name is required',
            'auth.phone_required': 'Phone number is required',
            'auth.id_required': 'National ID is required',
            'auth.reg_success_desc': "We've sent a verification link to your email. Please check your inbox to activate your account.",
            'auth.agree_to': 'I agree to the',
            'auth.terms_required': 'You must accept the terms',
            'auth.pass_match': 'Passwords do not match',
            'admin.analytics.title': 'Analytics Dashboard',
            'admin.analytics.subtitle': 'Comprehensive insights and performance metrics',
            'admin.analytics.revenue_trends': 'Revenue Trends',
            'admin.analytics.category_breakdown': 'Category Breakdown',
            'admin.analytics.top_events': 'Top Performing Events',
            'admin.analytics.total_revenue': 'Total Revenue',
            'admin.analytics.total_bookings': 'Total Bookings',
            'admin.analytics.avg_price': 'Avg Ticket Price',
            'admin.analytics.conv_rate': 'Conversion Rate',
            'admin.analytics.period.week': 'Week',
            'admin.analytics.period.month': 'Month',
            'admin.analytics.period.year': 'Year',
            'admin.analytics.export': 'Export',
            'admin.analytics.report': 'Report',
            'admin.analytics.rank': 'Rank',
            'admin.analytics.event_name': 'Event Name',
            'admin.analytics.bookings': 'Bookings',
            'admin.analytics.revenue': 'Revenue',
            'admin.analytics.avg_ticket': 'Avg/Ticket',
            'admin.analytics.growth': 'from last period',
            'profile.my_bookings': 'My Bookings',
            'profile.tabs.all': 'All',
            'profile.tabs.upcoming': 'Upcoming',
            'profile.tabs.past': 'Past',
            'profile.tabs.cancelled': 'Cancelled',
            'profile.no_bookings': 'No bookings found',
            'profile.no_bookings_desc': 'Browse our events or train schedules to make your first booking!',
            'profile.view_tickets': 'View Tickets',
            'profile.get_qr': 'Get QR Code',
            'profile.download': 'Download Ticket',
            'profile.cancel': 'Cancel Booking',
            'profile.delete': 'Delete History',
            'profile.continue_pay': 'Continue to Payment',
            'profile.id': 'Booking ID',
            'profile.status.booked': 'Confirmed',
            'profile.status.pending': 'Payment Pending',
            'profile.status.cancelled': 'Cancelled',
            'profile.status.expired': 'Expired',
            'profile.cancel_confirm': 'Are you sure you want to cancel this booking?',
            'profile.refund_policy': 'Refund Policy: Cancellation is only allowed 24 hours before the event.\n\nAre you sure you want to request a refund?',
            'profile.delete_confirm': 'Are you sure you want to delete this booking from your history?',
            'profile.cancel_success': 'Booking cancelled successfully',
            'profile.cancel_failed': 'Failed to cancel booking',
            'profile.scan_at_gate': 'Scan this QR code at the gate for entry',
            'profile.close': 'Close',
            'profile.total': 'Total',
            'profile.booked_on': 'Booked On',
            'profile.seats': 'Seats',
            'profile.to': 'to',
            'trains.book_now': 'Book Now',
            'trains.confirming': 'Confirming...',
            'trains.terms_footnote': '* By clicking "Book Now" you agree to the railway terms of service. National ID must match the person traveling.',
            'trains.max_seats_alert': 'You can select maximum 4 seats per booking.',
            'trains.select_seat_alert': 'Please select at least one seat.',
            'trains.id_required_alert': 'National ID is required for train bookings.',
            'trains.booking_failed_alert': 'Booking failed. Please try again.',
            'trains.error_load_availability': 'Could not load seat map. Please try again.',
            'trains.seat': 'Seat',
            'trains.total_amount': 'Total Amount',
            'booking.max_seats_alert': 'You can only select up to 10 seats.',
            'booking.session_expired_alert': 'Session expired! Your seats have been released.',
            'booking.login_required_confirm': 'You need to login to complete the booking. Proceed to login?',
            'booking.sold_out_alert': 'Sorry, this section is sold out.',
            'booking.booking_failed_alert': 'Failed to reserve seats. They may have just been taken.',
            'booking.error_payment_failed': 'Payment failed',
            'booking.error_processing': 'Payment processing error. Please try again.',
            'booking.error_initiate': 'Could not initiate payment. Please try again.',
            'booking.error_confirm_failed': 'Payment succeeded but booking update failed. Contact support.',
            'booking.download_ticket': 'Downloading ticket as PDF...',
            'booking.share_ticket_title': 'My Match Ticket',
            'booking.share_ticket_text': 'Ready for the game!',
            'booking.share_ticket_success': 'Ticket link copied to clipboard!',
            'booking.add_calendar': 'Adding match to calendar...',
            'common.egp': 'EGP',
            'profile.your_ticket': 'Your Ticket',
            'contact.name_label': 'Full Name',
            'contact.phone_label': 'Phone Number',
            'Cairo': 'Cairo',
            'Alexandria': 'Alexandria',
            'Luxor': 'Luxor',
            'Aswan': 'Aswan',
            'Port Said': 'Port Said',
            'Asyuit': 'Asyuit',
            'Giza': 'Giza',
            'Suez': 'Suez',
            'Mansoura': 'Mansoura',
            'Ismailia': 'Ismailia',
            'Minya': 'Minya',
            'Sohag': 'Sohag',
            'Qena': 'Qena',
            'Hurghada': 'Hurghada',
            'Sharm El Sheikh': 'Sharm El Sheikh',
            'Tanta': 'Tanta',
            'Damanhour': 'Damanhour',
            'Express': 'Express',
            'VIP': 'VIP',
            'AC': 'AC',
            'Ordinary': 'Ordinary',
            'Spanish': 'Spanish',
            'Special': 'Special',
            'First Class': 'First Class',
            'Second Class': 'Second Class'
        },
        ar: {
            'nav.home': 'الرئيسية',
            'nav.sports': 'الرياضة',
            'nav.entertainment': 'الترفيه',
            'nav.trains': 'القطارات',
            'nav.stores': 'الفروع',
            'nav.faq': 'الأسئلة الشائعة',
            'nav.about': 'من نحن',
            'nav.contact': 'اتصل بنا',
            'nav.ai_assistant': 'المساعد الذكي',
            'nav.login': 'تسجيل الدخول',
            'nav.signup': 'إنشاء حساب',
            'nav.my_bookings': 'حجوزاتي',
            'nav.settings': 'الإعدادات',
            'nav.logout': 'تسجيل الخروج',
            'nav.admin_dashboard': 'لوحة التحكم',
            'nav.notifications': 'التنبيهات',
            'nav.no_notifications': 'لا توجد تنبيهات جديدة',
            'home.title': 'تذكرتي',
            'home.subtitle': 'شريكك الأول لحجز تذاكر الفعاليات في مصر',
            'home.search_placeholder': 'ابحث عن فنان، فعالية، أو مكان...',
            'home.search_btn': 'بحث',
            'home.featured_title': 'أهم الفعاليات',
            'home.featured_subtitle': 'المباريات والعروض الأكثر انتظاراً',
            'home.view_all': 'عرض الكل',
            'home.book_now': 'احجز تذكرتك الآن',
            'Cairo International Stadium': 'استاد القاهرة الدولي',
            'Borg El Arab Stadium': 'استاد برج العرب',
            'Suez Canal Stadium': 'استاد قناة السويس',
            'Al Ahly': 'الأهلي',
            'Zamalek': 'الزمالك',
            'Al Masry': 'المصري',
            'Pyramids': 'بيراميدز',
            'Modern Future': 'مودرن فيوتشر',
            'Egyptian Premier League': 'الدوري المصري الممتاز',
            'Egypt Cup': 'كأس مصر',
            'home.why_title': 'لماذا تذكرتي؟',
            'home.why_subtitle': 'نوفر لك تجربة الحجز الأكثر سهولة وأماناً في مصر.',
            'home.instant_booking': 'حجز فوري',
            'home.instant_desc': 'وفر وقتك. احجز تذكرتك في ثوانٍ معدودة من خلال نظام دفع متطور.',
            'home.diverse_selection': 'خيارات متنوعة',
            'home.diverse_desc': 'من الحفلات الموسيقية إلى مباريات الاستاد، لدينا أكبر تشكيلة من الفعاليات.',
            'home.secure_payments': 'دفع آمن',
            'home.secure_desc': 'أمان عالي المستوى مع تكامل Stripe لضمان سلامة بياناتك دائماً.',
            'trains.hero_title': 'فن السفر',
            'trains.hero_subtitle': 'رحلات قطار سلسة من القاهرة',
            'trains.hero_desc': 'من عظمة النيل الخالدة إلى نسيم المتوسط. استمتع بتراث مصر براحة وفخامة لا مثيل لهما.',
            'trains.where_to': 'إلى أين؟',
            'trains.travel_date': 'تاريخ السفر',
            'trains.search_trains': 'بحث عن قطارات',
            'trains.available_expeditions': 'الرحلات المتاحة',
            'trains.transit': 'مدة الرحلة',
            'trains.departure': 'المغادرة',
            'trains.arrival': 'الوصول',
            'trains.intermediate_stops': 'محطات توقف',
            'trains.no_trains_found': 'لم يتم العثور على رحلات',
            'trains.no_trains_found_desc': 'عذراً، لم نتمكن من العثور على جداول قطارات متاحة لهذه الوجهة في الوقت الحالي.',
            'trains.syncing': 'جاري تحديث الجداول...',
            'trains.voyage_to': 'رحلة إلى',
            'ai.title': 'nada',
            'ai.subtitle': 'مساعدك الشخصي للسفر والفعاليات',
            'ai.quick_questions': 'أسئلة شائعة',
            'ai.new_chat': 'محادثة جديدة',
            'ai.chat_with': 'تحدث مع ندى',
            'ai.chat_desc': 'اسألني عن الفعاليات، مواعيد القطارات، أو الحجوزات!',
            'ai.online': 'متصل',
            'ai.meet_nada': 'تعرف على ندى',
            'ai.meet_nada_desc': 'أنا مساعدك الذكي. يمكنني مساعدتك في اكتشاف الفعاليات المثيرة، والتحقق من مواعيد القطارات، وإدارة حجزواتك في جميع أنحاء مصر.',
            'ai.you': 'أنت',
            'ai.placeholder': 'اسأل عن الفعاليات، القطارات، أو المساعدة...',
            'ai.send': 'إرسال',
            'ai.disclaimer': 'قد لا تكون ردود الذكاء الاصطناعي دقيقة دائماً. يرجى مراجعة القوائم الرسمية للحصول على التحديثات الهامة.',
            'ai.welcome_guest': "أهلاً بك! 👋 أنا ندى، مساعد تذكرتي الذكي. للحصول على أفضل تجربة وتوصيات مخصصة، يرجى تسجيل الدخول إلى حسابك.",
            'ai.welcome_auth': "أهلاً بك! 👋 أنا ندى، مساعد تذكرتي الذكي. يمكنني مساعدتك في العثور على الفعاليات، وحجز التذاكر، والحصول على توصيات ذكية. ماذا تود أن تفعل اليوم؟",
            'ai.error_session': 'عذراً، لم أتمكن من بدء جلسة دردشة. يرجى المحاولة مرة أخرى لاحقاً.',
            'ai.error_message': 'عذراً، حدث خطأ ما أثناء التحدث مع الذكاء الاصطناعي. يرجى المحاولة مرة أخرى.',
            'ai.confirm_new_chat': 'هل تريد بدء محادثة جديدة؟ سيتم مسح المحادثة الحالية.',
            'ai.suggestion.movies': 'ما هي الأفلام المعروضة هذا الأسبوع؟',
            'ai.suggestion.concerts': 'عرض الحفلات الموسيقية القريبة مني',
            'ai.suggestion.alex_train': 'كيف يمكنني حجز قطار إلى الإسكندرية؟',
            'ai.suggestion.tomorrow_trains': 'ما هي مواعيد قطارات الغد؟',
            'ai.suggestion.recommendations': 'أريد بعض التوصيات',
            'ai.suggestion.carriage': 'كيف يمكنني اختيار نوع العربة؟',
            'ai.suggestion.train_seats': 'هل توجد مقاعد متاحة لأسوان؟',
            'ai.example.today': '🎬 ماذا يعرض اليوم؟',
            'ai.example.weekend': '🎵 أي حفلات نهاية الأسبوع؟',
            'ai.example.aswan': '🚆 مواعيد قطارات القاهرة إلى أسوان',
            'ai.example.sports': '⚽ فعاليات رياضية قريبة',
            'ai.example.recommend': '💡 اقترح لي شيئاً',
            'ai.example.train_how': '📱 كيف أحجز تذكرة قطار؟',
            'events.sports_title': 'الأحداث',
            'events.sports_subtitle': 'احجز مقعدك لأكثر المباريات والبطولات إثارة في مصر.',
            'events.ent_title': 'عروض',
            'events.ent_subtitle': 'استمتع بسحر السينما، الموسيقى والمسرح.',
            'events.discover_title': 'اكتشف الفعاليات',
            'events.discover_subtitle': 'تصفح الأفلام والحفلات والعروض القادمة بالقرب منك.',
            'events.choose_team': 'اختر الفريق',
            'events.stadium': 'الاستاد',
            'events.tournament': 'البطولة',
            'events.all_teams': 'جميع الفرق',
            'events.all_stadiums': 'جميع الملاعب',
            'events.all_tournaments': 'جميع البطولات',
            'events.clear_filters': 'مسح الفلاتر',
            'events.events_found': 'فعالية تم العثور عليها',
            'events.no_matches': 'لا توجد مباريات',
            'events.no_events': 'لا توجد فعاليات',
            'events.no_matches_desc': 'لم نتمكن من العثور على أي مباريات للفريق المختار أو المعايير المحددة.',
            'events.no_events_desc': 'لم نتمكن من العثور على أي فعاليات تطابق اختياراتك.',
            'events.previous': 'السابق',
            'events.next': 'التالي',
            'events.page': 'صفحة',
            'events.of': 'من',
            'events.tag.category': 'الفئة',
            'events.tag.venue': 'فلتر المكان',
            'events.tag.search': 'بحث',
            'events.tag.team': 'فريق',
            'events.tag.stadium': 'ملعب',
            'events.tag.tournament': 'بطولة',
            'events.sold_out': 'مباع بالكامل',
            'events.ai_pick': 'اختيار الذكاء الاصطناعي',
            'events.trending': 'شائع الآن',
            'events.start_from': 'يبدأ من',
            'events.book': 'حجز',
            'events.unavailable': 'غير متاح',
            'events.about': 'عن الفعالية',
            'events.select_section': 'اختر الدرجة / القسم',
            'events.select_showtime': 'اختر وقت العرض',
            'events.booking_details': 'تفاصيل الحجز',
            'events.secure_spot': 'احجز مكانك الآن',
            'events.selected_section': 'القسم المختار',
            'events.fan_id': 'الرقم التعريفي (تلقائي)',
            'events.full_name': 'الاسم بالكامل',
            'events.ticket_count': 'عدد التذاكر',
            'events.discount_code': 'كود الخصم / QR',
            'events.apply': 'تطبيق',
            'events.total_amount': 'إجمالي المبلغ',
            'events.book_now': 'احجز الآن',
            'events.select_seats': 'اختيار المقاعد',
            'events.date': 'التاريخ',
            'events.time': 'الوقت',
            'events.price': 'السعر',
            'events.gate': 'بوابة',
            'events.section_guide': 'يرجى اختيار قسم للمتابعة',
            'events.showtime_guide': 'يرجى اختيار وقت عرض للمتابعة',
            'events.loading_details': 'جاري تحميل تفاصيل الفعالية...',
            'events.discount_placeholder': 'أدخل الكود',
            'events.discount_success': 'تم تطبيق الخصم!',
            'events.secure_proceed': 'المتابعة للدفع الآمن',
            'events.power_by': 'مدعوم بنظام دفع تذكرتي الآمن',
            'events.not_found': 'الفعالية غير موجودة',
            'events.back_to_list': 'العودة للفعاليات',
            'events.no_shows': 'لا توجد مواعيد عرض متاحة حالياً.',
            'events.no_sections': 'لا توجد معلومات عن الأقسام حالياً.',
            'footer.about_text': 'وجهتك الأولى لحجز تذاكر الفعاليات والسينما في مصر.',
            'footer.quick_links': 'روابط سريعة',
            'footer.support': 'الدعم',
            'footer.contact_us': 'اتصل بنا',
            'footer.help_center': 'مركز المساعدة',
            'footer.terms': 'شروط الخدمة',
            'footer.privacy': 'سياسة الخصوصية',
            'footer.refund_policy': 'سياسة الاسترجاع',
            'footer.rights': 'جميع الحقوق محفوظة.',
            'sports.title': 'الأحداث',
            'sports.events': 'الرياضية',
            'sports.subtitle': 'احجز مقعدك لأكثر المباريات والبطولات إثارة في مصر.',
            'ent.title': 'عروض',
            'ent.shows': 'الترفيه',
            'ent.subtitle': 'استمتع بسحر السينما، الموسيقى، والمسرح.',
            'common.no_results': 'لا توجد نتائج',
            'common.loading': 'جاري التحميل...',
            'common.featured': 'مميز',
            'team.Al Ahly': 'الأهلي',
            'team.Zamalek': 'الزمالك',
            'team.Al Masry': 'المصري',
            'team.Pyramids': 'بيراميدز',
            'team.Modern Future': 'مودرن فيوتشر',
            'tournament.Egyptian Premier League': 'الدوري المصري الممتاز',
            'tournament.Egypt Cup': 'كأس مصر',
            'stadium.Cairo International Stadium': 'استاد القاهرة الدولي',
            'stadium.Borg El Arab Stadium': 'استاد برج العرب',
            'stadium.Suez Canal Stadium': 'استاد قناة السويس',
            'faq.title': 'الأسئلة الشائعة',
            'faq.q1': 'كيف يمكنني حجز تذكرة؟',
            'faq.a1': 'يمكنك حجز التذاكر مباشرة من خلال موقعنا عن طريق اختيار الفعالية واختيار مقاعدك المفضلة ثم المتابعة للدفع.',
            'faq.q2': 'أين يمكنني استلام التذكرة المطبوعة؟',
            'faq.a2': 'يمكنك زيارة أي من فروعنا المعتمدة المدرجة في صفحة "الفروع". يرجى إحضار رقم الحجز وبطاقة الهوية.',
            'faq.q3': 'هل يمكنني إلغاء أو استرداد قيمة التذكرة؟',
            'faq.a3': 'تختلف سياسات الاسترداد حسب منظم الفعالية. عادةً يمكن الاسترداد حتى 48 ساعة قبل بدء الفعالية.',
            'faq.q4': 'كيف يمكنني الوصول إلى تذكرتي الإلكترونية؟',
            'faq.a4': 'بعد الدفع الناجح، ستكون تذكرتك (QR code) متاحة في قسم "حجوزاتي" في ملفك الشخصي.',
            'faq.q5': 'هل أحتاج لطباعة التذكرة؟',
            'faq.a5': 'بالنسبة لمعظم الفعاليات، يكفي وجود كود QR على هاتفك. ومع ذلك، قد تطلب بعض الأماكن تذكرة مطبوعة.',
            'faq.q6': 'هل الدفع عبر الإنترنت آمن؟',
            'faq.a6': 'نعم، نحن نستخدم تشفيراً قياسياً وبوابات دفع آمنة لضمان حماية بياناتك المالية.',
            'store.cairo.name': 'مركز تذكرتي القاهرة الرئيسي',
            'store.alex.name': 'تذكرتي الإسكندرية - الكورنيش',
            'store.giza.name': 'مكتب تذكرتي الأهرامات',
            'store.nasr.name': 'فرع مدينة نصر - سيتي ستارز',
            'store.cairo.addr': '123 شارع وسط البلد، القاهرة',
            'store.alex.addr': '45 طريق الكورنيش، الإسكندرية',
            'store.giza.addr': '88 شارع الهرم، الجيزة',
            'store.nasr.addr': 'سيتي ستارز مول، المرحلة الثانية',
            'store.hours': 'ساعات العمل',
            'store.view_map': 'عرض على الخريطة',
            'store.subtitle': 'قم بزيارة مراكز التذاكر المعتمدة لدينا لشراء التذاكر، أو استلام الحجوزات، أو الحصول على المساعدة.',
            'store.official': 'فرع رسمي',
            'common.address': 'العنوان',
            'common.phone': 'الهاتف',
            'common.select': 'اختيار',
            'common.general': 'عام',
            'common.venue': 'المكان',
            'common.stadium': 'الاستاد',
            'common.and': 'و',
            'common.cairo_egypt': 'القاهرة، مصر',
            'Venue': 'مكان الفعالية',
            'Stadium': 'الاستاد',
            'TBA': 'قريباً',
            'common.id': 'المعرف',
            'common.na': 'غير متاح',
            'Sports': 'رياضة',
            'Entertainment': 'ترفيه',
            'movie': 'سينما',
            'concert': 'حفلة',
            'sports': 'رياضة',
            'show': 'عرض',
            'entertainment': 'ترفيه',
            'trains': 'قطارات',
            'home.stay_tuned': 'انتظرونا قريباً!',
            'home.stay_tuned_desc': 'يقوم فريقنا حالياً باختيار أكثر الفعاليات إثارة من أجلك. عد قريباً لمشاهدة أهم الفعاليات!',
            'contact.get_in_touch': 'تواصل معنا',
            'contact.title': 'اتصل بنا',
            'contact.subtitle': 'هل لديك استفسارات حول حجزك؟ هل تحتاج إلى دعم فني؟ نحن هنا للمساعدة!',
            'contact.support_title': 'دعم العملاء',
            'contact.support_desc': 'فريق الدعم لدينا متاح على مدار الساعة طوال أيام الأسبوع لمساعدتك.',
            'contact.email_title': 'راسلنا',
            'contact.email_desc': 'أرسل لنا بريداً إلكترونياً وسنرد عليك في غضون 24 ساعة.',
            'contact.hq_title': 'المقر الرئيسي',
            'contact.hq_addr': '123 شارع التكنولوجيا، حي المدينة الرقمية، القاهرة، مصر',
            'contact.form_title': 'أرسل لنا رسالة',
            'contact.form_success': 'تم إرسال الرسالة!',
            'contact.form_success_desc': 'شكراً لتواصلك معنا. سنقوم بالرد عليك قريباً.',
            'contact.name': 'الاسم بالكامل',
            'contact.name_placeholder': 'أدخل اسمك...',
            'contact.email': 'البريد الإلكتروني',
            'contact.email_placeholder': 'بريدك الإلكتروني...',
            'contact.subject': 'الموضوع',
            'contact.subject_placeholder': 'اختر الموضوع...',
            'contact.msg': 'الرسالة',
            'contact.msg_placeholder': 'كيف يمكننا مساعدتك؟',
            'contact.btn_sending': 'جاري الإرسال...',
            'contact.btn_send': 'إرسال الرسالة',
            'contact.topic.general': 'استفسار عام',
            'contact.topic.booking': 'دعم الحجوزات',
            'contact.topic.tech': 'مشكلة تقنية',
            'contact.topic.feedback': 'آراء وملاحظات',
            'contact.topic.partnership': 'شراكة',
            'faq.support_center': 'مركز الدعم',
            'faq.subtitle': 'ابحث عن إجابات للأسئلة الشائعة حول الحجز، الدفع، وحضور الفعاليات.',
            'faq.still_questions': 'لا يزال لديك أسئلة؟',
            'faq.contact_support': 'اتصل بالدعم',
            'faq.still_desc': 'فريق الدعم لدينا متاح على مدار الساعة طوال أيام الأسبوع للإجابة على أي أسئلة أخرى قد تكون لديكم حول خدماتنا.',
            'faq.title_white': 'الأسئلة',
            'faq.title_green': 'الشائعة',
            'contact.title_white': 'تواصل',
            'contact.title_green': 'معنا',
            'store.title_white': 'فروعنا',
            'store.title_green': 'المعتمدة',
            'about.our_story': 'قصتنا',
            'about.title': 'عن تذكرتي',
            'about.subtitle': 'تذكرتي هي وجهتك الأولى لحجز الفعاليات الرياضية والترفيهية. نحن نصل بين المشجعين وتجاربهم المفضلة من خلال منصة سلسة وآمنة وسهلة الاستخدام.',
            'about.meet_dev': 'تعرف على المطور',
            'about.dev_exclusively': 'تم تطوير هذا التطبيق حصرياً بواسطة',
            'about.role': 'كبير المطورين والمهندس المعماري للبرمجيات',
            'about.bio': 'مطور متكامل شغوف مكرس لبناء تجارب رقمية سلسة وبديهية. تذكرتي هي ثمرة التقنيات الويب الحديثة المصممة لتبسيط حجز الفعاليات.',
            'about.special_thanks': 'شكر خاص وتقدير',
            'about.vision_support': 'أصبح هذا المشروع ممكناً بفضل الدعم غير المشروط والتشجيع من أصدقائي وزملائي. شكراً لإيمانكم بالرؤية.',
            'stepper.select_seats': 'اختيار المقاعد',
            'stepper.checkout': 'الدفع',
            'stepper.confirmation': 'التأكيد',
            'settings.title': 'إعدادات الحساب',
            'settings.subtitle': 'إدارة ملفك الشخصي وتفضيلاتك',
            'settings.profile': 'الملف الشخصي',
            'settings.security': 'الأمان',
            'settings.notifications': 'التنبيهات',
            'settings.account_mgmt': 'الحساب',
            'settings.profile_info': 'معلومات الملف الشخصي',
            'settings.security_settings': 'إعدادات الأمان',
            'settings.notif_prefs': 'تفضيلات التنبيهات',
            'settings.danger_zone': 'إدارة الحساب',
            'settings.full_name': 'الاسم بالكامل',
            'settings.email': 'البريد الإلكتروني',
            'settings.phone': 'رقم الهاتف',
            'settings.save_changes': 'حفظ التغييرات',
            'settings.saving': 'جاري الحفظ...',
            'settings.current_pass': 'كلمة المرور الحالية',
            'settings.new_pass': 'كلمة المرور الجديدة',
            'settings.confirm_pass': 'تأكيد كلمة المرور الجديدة',
            'settings.change_pass': 'تغيير كلمة المرور',
            'settings.update_success': 'تم تحديث الملف الشخصي بنجاح!',
            'settings.update_failed': 'فشل تحديث الملف الشخصي',
            'settings.email_notif': 'تنبيهات البريد الإلكتروني',
            'settings.email_notif_desc': 'استلام تأكيدات الحجز عبر البريد الإلكتروني',
            'settings.push_notif': 'التنبيهات اللحظية',
            'settings.push_notif_desc': 'الحصول على تحديثات حول حجوزاتك',
            'settings.reminders': 'تذكيرات الفعاليات',
            'settings.reminders_desc': 'احصل على تذكير بالفعاليات القادمة',
            'settings.promo': 'العروض الترويجية',
            'settings.promo_desc': 'استلام العروض الخاصة والخصومات',
            'settings.download_data': 'تحميل بياناتك',
            'settings.download_data_desc': 'احصل على نسخة من جميع حجوزاتك ومعلومات حسابك',
            'settings.download_btn': 'تحميل البيانات',
            'settings.delete_account': 'حذف الحساب',
            'settings.delete_account_desc': 'حذف حسابك وجميع البيانات المرتبطة به نهائياً. لا يمكن التراجع عن هذا الإجراء.',
            'settings.delete_btn': 'حذف حسابي',
            'settings.delete_confirm': 'هل أنت متأكد من رغبتك في حذف حسابك؟ لا يمكن التراجع عن هذا الإجراء!',
            'settings.delete_really': 'هل أنت متأكد حقاً؟ سيتم حذف جميع بياناتك نهائياً!',
            'settings.delete_request': 'تم تقديم طلب حذف الحساب. يرجى التواصل مع الدعم.',
            'booking.back_to_event': 'العودة للفعالية',
            'booking.back_to_overview': 'العودة لتفاصيل التذاكر',
            'booking.gates_open': 'فتح الأبواب',
            'booking.match_start': 'بدء المباراة',
            'booking.showtime': 'وقت العرض',
            'booking.confirm_booking': 'تأكيد الحجز',
            'booking.select_seats': 'اختيار المقاعد',
            'booking.select_seats_desc': 'انقر على المقاعد المتاحة لاختيارها أو إلغاء اختيارها',
            'booking.loading': 'جاري التحميل...',
            'booking.sports_event': 'حدث رياضي',
            'booking.match_day': 'يوم المباراة',
            'booking.attendee': 'الحاضر',
            'booking.guest_user': 'زائر',
            'booking.section': 'القسم',
            'booking.tickets_count': 'تذكرة',
            'booking.scan_gate': 'امسح الكود عند البوابة',
            'booking.ref_id': 'رقم المرجع',
            'booking.need_to_know': 'معلومات هامة',
            'booking.sports_seat_guide': 'يمكنك الجلوس في أي مقعد متاح داخل القسم. يرجى الحضور مبكراً للحصول على أفضل الأماكن!',
            'booking.sold_out': 'مباع بالكامل',
            'booking.browse_other': 'تصفح فعاليات أخرى',
            'booking.no_map': 'لا توجد خريطة مقاعد متاحة لهذا العرض.',
            'booking.available': 'متاح',
            'booking.selected': 'مختار',
            'booking.occupied': 'محجوز',
            'booking.vip': 'في أي بي',
            'booking.summary': 'ملخص الحجز',
            'booking.selected_seats': 'المقاعد المختارة',
            'booking.max': 'الحد الأقصى',
            'booking.no_seats_selected': 'لم يتم اختيار أي مقاعد بعد.',
            'booking.click_map_start': 'انقر على الخريطة للبدء.',
            'booking.ticket_price': 'سعر التذكرة',
            'booking.booking_fee': 'رسوم الحجز',
            'booking.total': 'الإجمالي',
            'booking.checkout': 'المتابعة للدفع',
            'booking.processing': 'جاري المعالجة...',
            'booking.terms_agree': 'بمتابعتك، فإنك توافق على شروط الخدمة الخاصة بنا.',
            'booking.secure_checkout': 'دفع آمن',
            'booking.secure_checkout_desc': 'أكمل حجزك بأمان عبر Stripe',
            'admin.dashboard': 'لوحة التحكم',
            'admin.welcome': 'مرحباً بك مجدداً!',
            'admin.happening_today': 'إليك ما يحدث في تذكرتي اليوم.',
            'admin.refresh': 'تحديث',
            'admin.export': 'تصدير تقرير',
            'admin.total_revenue': 'إجمالي الإيرادات',
            'admin.total_bookings': 'إجمالي الحجوزات',
            'admin.active_sports': 'الفعاليات الرياضية النشطة',
            'admin.total_users': 'إجمالي المستخدمين',
            'admin.vs_last_month': 'مقارنة بالشهر الماضي',
            'admin.recent_bookings': 'أحدث الحجوزات',
            'admin.view_all': 'عرض الكل',
            'admin.loading_bookings': 'جاري تحميل الحجوزات...',
            'admin.no_bookings': 'لا توجد حجوزات حديثة',
            'admin.new_bookings_appear': 'ستظهر الحجوزات الجديدة هنا',
            'admin.quick_actions': 'إجراءات سريعة',
            'admin.manage_sports': 'إدارة الفعاليات الرياضية',
            'admin.manage_stadiums': 'إدارة الاستادات',
            'admin.manage_venues': 'إدارة القاعات',
            'admin.manage_ent': 'إدارة الفعاليات الترفيهية',
            'admin.manage_users': 'إدارة المستخدمين',
            'admin.view_analytics': 'عرض التحليلات',
            'admin.system_status': 'حالة النظام',
            'admin.api_status': 'حالة API',
            'admin.database': 'قاعدة البيانات',
            'admin.socket_io': 'Socket.IO',
            'admin.payment_gateway': 'بوابة الدفع',
            'admin.online': 'متصل',
            'admin.connected': 'متصل',
            'admin.active': 'نشط',
            'admin.event_mgmt': 'إدارة الفعاليات',
            'admin.event_mgmt_desc': 'إدارة جميع الفعاليات، الأفلام، الحفلات والعروض',
            'admin.create_event': 'إنشاء فعالية',
            'admin.search_placeholder': 'البحث بالعنوان...',
            'admin.all_cities': 'جميع المدن',
            'admin.all_championships': 'جميع البطولات',
            'admin.loading_events': 'جاري تحميل الفعاليات...',
            'admin.active_badge': 'نشط',
            'admin.inactive_badge': 'غير نشط',
            'admin.featured_badge': 'مميز',
            'admin.edit': 'تعديل',
            'admin.delete': 'حذف',
            'admin.no_events_found': 'لم يتم العثور على فعاليات',
            'admin.adjust_filters': 'يرجى تجربة تغيير الفلاتر',
            'admin.save': 'حفظ',
            'admin.cancel': 'إلغاء',
            'admin.update': 'تحديث',
            'admin.create': 'إنشاء',
            'admin.title': 'العنوان',
            'admin.description': 'الوصف',
            'admin.poster': 'بوستر الفعالية',
            'admin.match_details': 'تفاصيل المباراة',
            'admin.stadium': 'الاستاد',
            'admin.home_team': 'الفريق المضيف',
            'admin.away_team': 'الفريق الضيف',
            'admin.total_cap': 'السعة الإجمالية',
            'admin.home_cap': 'جمهور المضيف',
            'admin.away_cap': 'جمهور الضيف',
            'admin.gates_open': 'فتح الأبواب في',
            'admin.duration': 'المدة (دقيقة)',
            'admin.release_date': 'تاريخ الإصدار',
            'admin.user_mgmt': 'إدارة المستخدمين',
            'admin.user_mgmt_desc': 'إدارة جميع المستخدمين المسجلين',
            'admin.export_users': 'تصدير المستخدمين',
            'admin.search_users_placeholder': 'البحث بالاسم أو البريد...',
            'admin.role': 'الدور',
            'admin.all_roles': 'كل الأدوار',
            'admin.user': 'مستخدم',
            'admin.admin': 'مسؤول',
            'admin.joined': 'انضم في',
            'admin.bookings': 'الحجوزات',
            'admin.spent': 'إجمالي الإنفاق',
            'admin.view': 'عرض',
            'admin.upgrade': 'ترقية',
            'admin.downgrade': 'تنزيل المرتبة',
            'admin.no_users_found': 'لم يتم العثور على مستخدمين',
            'admin.loading_users': 'جاري تحميل المستخدمين...',
            'admin.account_status': 'حالة الحساب',
            'admin.close': 'إغلاق',
            'admin.phone': 'الهاتف',
            'admin.stadium_mgmt': 'إدارة الاستادات',
            'admin.stadium_mgmt_desc': 'إدارة الاستادات والملاعب والمرافق الرياضية',
            'admin.add_stadium': 'إضافة استاد جديد',
            'admin.search_stadiums_placeholder': 'البحث بالاسم أو الموقع...',
            'admin.status_filter': 'فلتر الحالة',
            'admin.all_stadiums': 'جميع الاستادات',
            'admin.active_only': 'النشطة فقط',
            'admin.inactive_only': 'غير النشطة فقط',
            'admin.loading_stadiums': 'جاري تحميل الاستادات...',
            'admin.stadium_name': 'اسم الاستاد',
            'admin.location': 'الموقع',
            'admin.city': 'المدينة',
            'admin.capacity': 'السعة',
            'admin.manage_zones': 'إدارة المناطق/القاعات',
            'admin.no_stadiums_found': 'لم يتم العثور على استادات',
            'admin.stadium_usage_desc': 'حاول تعديل الفلاتر أو إنشاء استاد جديد',
            'admin.add_first_stadium': 'إضافة أول استاد',
            'admin.sections': 'الأقسام',
            'admin.add_section': 'إضافة قسم',
            'admin.no_sections_added': 'لا توجد أقسام مضافة.',
            'admin.edit_section': 'تعديل القسم',
            'admin.add_new_section': 'إضافة قسم جديد',
            'admin.section_name': 'اسم القسم',
            'admin.side_type': 'الجانب / النوع',
            'admin.gate_entrance': 'البوابة / المدخل',
            'admin.default_price': 'السعر الافتراضي',
            'admin.seat_breakdown': 'تقسيم المقاعد',
            'admin.fill_all_fields': '⚠️ يرجى ملء جميع الحقول المطلوبة (العنوان والوصف)',
            'admin.select_stadium_error': '⚠️ يرجى اختيار استاد للفعاليات الرياضية',
            'admin.select_teams_error': '⚠️ يرجى اختيار كل من الفريق المضيف والضيف',
            'admin.capacity_exceed_error': '⚠️ السعة الإجمالية تتجاوز سعة الاستاد!',
            'admin.capacity_sum_error': '⚠️ مجموع سعة المضيف والضيف يتجاوز سعة الاستاد!',
            'admin.event_update_success': '✅ تم تحديث الفعالية بنجاح!',
            'admin.event_update_failed': '❌ فشل في تحديث الفعالية',
            'admin.event_create_success': '✅ تم إنشاء الفعالية بنجاح!',
            'admin.event_create_failed': '❌ فشل في إنشاء الفعالية',
            'admin.event_delete_success': '✅ تم حذف الفعالية بنجاح!',
            'admin.event_delete_failed': '❌ فشل في حذف الفعالية',
            'admin.delete_confirm': 'هل أنت متأكد أنك تريد حذف هذه الفعالية؟',
            'admin.venue_mgmt': 'إدارة القاعات',
            'admin.venue_mgmt_desc': 'إدارة جميع القاعات والمسارح وأماكن الفعاليات',
            'admin.add_venue': 'إضافة قاعة جديدة',
            'admin.search_venues': 'البحث عن القاعات',
            'admin.search_venues_placeholder': 'البحث بالاسم أو الموقع...',
            'admin.all_venues': 'جميع القاعات',
            'admin.loading_venues': 'جاري تحميل القاعات...',
            'admin.no_venues_found': 'لم يتم العثور على قاعات',
            'admin.add_first_venue': 'إضافة أول قاعة',
            'admin.halls': 'القاعات الفرعية',
            'admin.manage_halls': 'إدارة القاعات',
            'admin.sellable': 'قابل للبيع',
            'admin.shows': 'العروض',
            'admin.bookings_exist': 'توجد حجوزات',
            'admin.edit_venue': 'تعديل القاعة',
            'admin.create_venue': 'إنشاء قاعة جديدة',
            'admin.venue_name': 'اسم القاعة',
            'admin.venue_location': 'الموقع',
            'admin.venue_city': 'المدينة',
            'admin.venue_capacity': 'السعة الإجمالية',
            'admin.venue_image': 'رابط الصورة',
            'admin.venue_description': 'الوصف',
            'admin.saving': 'جاري الحفظ...',
            'admin.delete_venue_confirm': 'هل أنت متأكد أنك تريد حذف هذه القاعة؟',
            'admin.delete_venue_warning': 'لا يمكن التراجع عن هذا الإجراء!',
            'admin.hall_name': 'اسم القاعة الفرعية',
            'admin.hall_capacity': 'سعة القاعة الفرعية',
            'admin.seat_breakdown_opt': 'تقسيم المقاعد (اختياري)',
            'admin.add_hall': 'إضافة قاعة فرعية',
            'admin.edit_hall': 'تعديل القاعة الفرعية',
            'admin.save_hall': 'حفظ القاعة',
            'admin.seat_map': 'خريطة المقاعد',
            'admin.venue_create_success': '✅ تم إنشاء القاعة بنجاح',
            'admin.venue_update_success': '✅ تم تحديث القاعة بنجاح',
            'admin.venue_delete_success': '✅ تم حذف القاعة بنجاح',
            'admin.hall_save_success': '✅ تم حفظ القاعة بنجاح',
            'admin.hall_save_error': '❌ فشل في حفظ القاعة',
            'admin.hall_delete_success': '✅ تم حذف القاعة الفرعية بنجاح',
            'admin.fill_required_fields': '⚠️ يرجى ملء جميع الحقول المطلوبة',
            'admin.venue_load_failed': '❌ فشل في تحميل القاعات',
            'admin.venue_save_failed': '❌ فشل في حفظ القاعة',
            'admin.venue_delete_failed': '❌ فشل في حذف القاعة',
            'admin.venue_activated': '✅ تم تفعيل القاعة بنجاح',
            'admin.venue_deactivated': '✅ تم إلغاء تفعيل القاعة بنجاح',
            'booking.order_summary': 'ملخص الطلب',
            'booking.total_pay': 'إجمالي الدفع',
            'booking.secure_payment_title': 'دفع آمن 100%',
            'booking.secure_payment_desc': 'معلومات الدفع الخاصة بك مشفرة ومعالجة بأمان بواسطة Stripe.',
            'booking.payment_details': 'تفاصيل الدفع',
            'booking.card_number': 'رقم البطاقة',
            'booking.card_holder': 'صاحب البطاقة',
            'booking.expires': 'تاريخ الانتهاء',
            'booking.name_on_card': 'الاسم على البطاقة',
            'booking.card_info': 'معلومات البطاقة',
            'booking.pay_amount': 'ادفع',
            'booking.powered_by': 'مدعوم بواسطة',
            'booking.confirmed': 'تم تأكيد الحجز!',
            'booking.confirmed_desc': 'تذاكرك جاهزة! لقد أرسلنا بريداً إلكترونياً مفصلاً بتأكيد الحجز.',
            'booking.return_home': 'العودة للرئيسية',
            'trains.carriage': 'عربة',
            'trains.sync_station': 'جاري الاتصال بالمحطة...',
            'trains.layout': 'مخطط',
            'trains.res_summary': 'ملخص الحجز',
            'trains.national_id': 'الرقم القومي (مطلوب)',
            'trains.id_placeholder': '14 رقم',
            'auth.welcome': 'مرحباً بعودتك!',
            'auth.signin_desc': 'سجل دخولك للمتابعة في تذكرتي',
            'auth.email': 'البريد الإلكتروني',
            'auth.email_placeholder': 'you@example.com',
            'auth.password': 'كلمة المرور',
            'auth.password_placeholder': 'أدخل كلمة المرور',
            'auth.remember': 'تذكرني',
            'auth.forgot': 'نسيت كلمة المرور؟',
            'auth.signin': 'تسجيل الدخول',
            'auth.signing_in': 'جاري الدخول...',
            'auth.no_account': 'ليس لديك حساب؟',
            'auth.signup_now': 'سجل الآن',
            'auth.admin_login': 'دخول المسؤول',
            'auth.login_success': 'تم تسجيل الدخول بنجاح! جاري التحويل...',
            'auth.login_failed': 'فشل تسجيل الدخول. يرجى المحاولة مرة أخرى.',
            'auth.email_required': 'البريد الإلكتروني مطلوب',
            'auth.email_invalid': 'يرجى إدخال بريد إلكتروني صالح',
            'auth.pass_required': 'كلمة المرور مطلوبة (6 أحرف على الأقل)',
            'auth.signup': 'إنشاء حساب',
            'auth.signup_desc': 'انضم إلى تذكرتي اليوم وابدأ في استكشاف الفعاليات.',
            'auth.fullname': 'الاسم بالكامل',
            'auth.fullname_placeholder': 'أدخل اسمك بالكامل',
            'auth.phone': 'رقم الهاتف',
            'auth.phone_placeholder': '01xxxxxxxxx',
            'auth.national_id': 'الرقم القومي',
            'auth.id_placeholder': '14 رقم',
            'auth.confirm_pass': 'تأكيد كلمة المرور',
            'auth.register': 'تسجيل',
            'auth.registering': 'جاري إنشاء الحساب...',
            'auth.has_account': 'لديك حساب بالفعل؟',
            'auth.login_now': 'سجل دخولك الآن',
            'auth.reg_success': 'تم التسجيل بنجاح! يرجى تسجيل الدخول.',
            'auth.reg_failed': 'فشل التسجيل. يرجى المحاولة مرة أخرى.',
            'auth.name_required': 'الاسم بالكامل مطلوب',
            'auth.phone_required': 'رقم الهاتف مطلوب',
            'auth.id_required': 'الرقم القومي مطلوب',
            'auth.reg_success_desc': 'لقد أرسلنا رابط تفعيل إلى بريدك الإلكتروني. يرجى التحقق من صندوق الوارد لتفعيل حسابك.',
            'auth.agree_to': 'أوافق على',
            'auth.terms_required': 'يجب الموافقة على الشروط والأحكام',
            'auth.pass_match': 'كلمات المرور غير متطابقة',
            'admin.analytics.title': 'لوحة التحليلات',
            'admin.analytics.subtitle': 'رؤى شاملة ومقاييس الأداء',
            'admin.analytics.revenue_trends': 'اتجاهات الإيرادات',
            'admin.analytics.category_breakdown': 'تحليل الفئات',
            'admin.analytics.top_events': 'الفعاليات الأكثر نجاحاً',
            'admin.analytics.total_revenue': 'إجمالي الإيرادات',
            'admin.analytics.total_bookings': 'إجمالي الحجوزات',
            'admin.analytics.avg_price': 'متوسط سعر التذكرة',
            'admin.analytics.conv_rate': 'معدل التحويل',
            'admin.analytics.period.week': 'أسبوع',
            'admin.analytics.period.month': 'شهر',
            'admin.analytics.period.year': 'سنة',
            'admin.analytics.export': 'تصدير',
            'admin.analytics.report': 'تقرير',
            'admin.analytics.rank': 'الترتيب',
            'admin.analytics.event_name': 'اسم الفعالية',
            'admin.analytics.bookings': 'الحجوزات',
            'admin.analytics.revenue': 'الإيرادات',
            'admin.analytics.avg_ticket': 'متوسط/تذكرة',
            'admin.analytics.growth': 'عن الفترة السابقة',
            'profile.my_bookings': 'حجوزاتي',
            'profile.tabs.all': 'الكل',
            'profile.tabs.upcoming': 'القادمة',
            'profile.tabs.past': 'السابقة',
            'profile.tabs.cancelled': 'الملغاة',
            'profile.no_bookings': 'لا توجد حجوزات',
            'profile.no_bookings_desc': 'تصفح الفعاليات أو جداول القطارات لإجراء حجزك الأول!',
            'profile.view_tickets': 'عرض التذاكر',
            'profile.get_qr': 'الحصول على QR',
            'profile.download': 'تحميل التذكرة',
            'profile.cancel': 'إلغاء الحجز',
            'profile.delete': 'حذف من السجل',
            'profile.continue_pay': 'استكمال الدفع',
            'profile.id': 'رقم الحجز',
            'profile.status.booked': 'مؤكد',
            'profile.status.pending': 'في انتظار الدفع',
            'profile.status.cancelled': 'ملغى',
            'profile.status.expired': 'منتهي',
            'profile.cancel_confirm': 'هل أنت متأكد من رغبتك في إلغاء هذا الحجز؟',
            'profile.refund_policy': 'سياسة الاسترجاع: الإلغاء مسموح فقط قبل 24 ساعة من الفعالية.\n\nهل أنت متأكد من رغبتك في طلب استرداد؟',
            'profile.delete_confirm': 'هل أنت متأكد من رغبتك في حذف هذا الحجز من السجل؟',
            'profile.cancel_success': 'تم إلغاء الحجز بنجاح',
            'profile.cancel_failed': 'فشل إلغاء الحجز',
            'profile.scan_at_gate': 'امسح هذا الرمز عند البوابة للدخول',
            'profile.close': 'إغلاق',
            'profile.total': 'الإجمالي',
            'profile.booked_on': 'تاريخ الحجز',
            'profile.seats': 'المقاعد',
            'profile.to': 'إلى',
            'trains.book_now': 'احجز الآن',
            'trains.confirming': 'جاري التأكيد...',
            'trains.terms_footnote': '* بالنقر على "احجز الآن" فإنك توافق على شروط خدمة السكك الحديدية. يجب أن يتطابق الرقم القومي مع الشخص المسافر.',
            'trains.max_seats_alert': 'يمكنك اختيار 4 مقاعد كحد أقصى لكل حجز.',
            'trains.select_seat_alert': 'يرجى اختيار مقعد واحد على الأقل.',
            'trains.id_required_alert': 'الرقم القومي مطلوب لحجوزات القطارات.',
            'trains.booking_failed_alert': 'فشل الحجز. يرجى المحاولة مرة أخرى.',
            'trains.error_load_availability': 'تعذر تحميل خريطة المقاعد. يرجى المحاولة مرة أخرى.',
            'trains.seat': 'مقعد',
            'trains.total_amount': 'إجمالي المبلغ',
            'booking.max_seats_alert': 'يمكنك اختيار 10 مقاعد كحد أقصى.',
            'booking.session_expired_alert': 'انتهت الجلسة! تم تحرير مقاعدك.',
            'booking.login_required_confirm': 'تحتاج إلى تسجيل الدخول لإكمال الحجز. هل تود الذهاب لصفحة تسجيل الدخول؟',
            'booking.sold_out_alert': 'عذراً، هذا القسم مباع بالكامل.',
            'booking.booking_failed_alert': 'فشل حجز المقاعد. ربما تم حجزها من قبل مستخدم آخر.',
            'booking.error_payment_failed': 'فشل عملية الدفع',
            'booking.error_processing': 'خطأ في معالجة الدفع. يرجى المحاولة مرة أخرى.',
            'booking.error_initiate': 'تعذر بدء عملية الدفع. يرجى المحاولة مرة أخرى.',
            'booking.error_confirm_failed': 'تم الدفع بنجاح ولكن فشل تحديث حالة الحجز. يرجى التواصل مع الدعم.',
            'booking.download_ticket': 'جاري تحميل التذكرة بصيغة PDF...',
            'booking.share_ticket_title': 'تذكرتي للمباراة',
            'booking.share_ticket_text': 'مستعد للمباراة!',
            'booking.share_ticket_success': 'تم نسخ رابط التذكرة!',
            'booking.add_calendar': 'جاري إضافة المباراة للتقويم...',
            'common.egp': 'ج.م',
            'profile.your_ticket': 'تذكرتك',
            'contact.name_label': 'الاسم بالكامل',
            'contact.phone_label': 'رقم الهاتف',
            'Cairo': 'القاهرة',
            'Alexandria': 'الإسكندرية',
            'Luxor': 'الأقصر',
            'Aswan': 'أسوان',
            'Port Said': 'بورسعيد',
            'Asyuit': 'أسيوط',
            'Giza': 'الجيزة',
            'Suez': 'السويس',
            'Mansoura': 'المنصورة',
            'Ismailia': 'الإسماعيلية',
            'Minya': 'المنيا',
            'Sohag': 'سوهاج',
            'Qena': 'قنا',
            'Hurghada': 'الغردقة',
            'Sharm El Sheikh': 'شرم الشيخ',
            'Tanta': 'طنطا',
            'Damanhour': 'دمنهور',
            'Express': 'إكسبريس',
            'VIP': 'خدمة خاصة',
            'AC': 'مكيف',
            'Ordinary': 'عادي',
            'Spanish': 'أسباني',
            'Special': 'خاص',
            'First Class': 'درجة أولى',
            'Second Class': 'درجة ثانية'
        }
    };
}
